### ISSUE TITLE
P^2 3.3.x breaks compatibility to plot2dynmap

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/plot2dynmap#2]
```
[Plot2Dynmap] Task #2038 for Plot2Dynmap v3.2.0 generated an exception
java.lang.NoSuchMethodError: com.intellectualcrafters.plot.PS.getPlotsInWorld(Ljava/lang/String;)Ljava/util/Collection;
        at com.empcraft.plot2dynmap.Main.updatePlots(Main.java:218) ~[?:?]
        at com.empcraft.plot2dynmap.Main.access$1(Main.java:213) ~[?:?]
        at com.empcraft.plot2dynmap.Main$Plot2Update.run(Main.java:103) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-efe04b8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-efe04b8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-efe04b8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-efe04b8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-efe04b8]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

**Comment by boy0001** [comment]
https://www.dropbox.com/sh/lor5vc5z9idxuz5/AAAdiS08uoI4LQpPpuJbVrjga?dl=0

**Comment by EvilOlaf** [comment]
Looks good :+1:
